config = {
    "mixed_precision": True,
    "dataset_name": "imagenette",
    "batch_size": 512,
    "buffer_size": 512 * 2,
    "input_shape": [196, 196, 3],
    "image_size": 224,
    "num_classes": 10,
    "learning_rate": 1e-4,
    "weight_decay": 1e-4,
    "epochs": 100,
    "patch_size": 16,
    "embed_dim": 128,
    "chunk_size": 14,
    "r": 2,
    "num_layers": 6,
    "ffn_drop": 0.2,
    "attn_drop": 0.2,
    "num_heads": 1,
}
